/*
 *      machdep.h generated by machdep at Thu Jan 23 19:50:44 2014
 */

#ifndef __test__
#define __test__

#ifdef __APPLE__
#include <machine/endian.h>
#if __WORDSIZE == 32
#define MACH_32_BIT_CPU
#else
#define MACH_64_BIT_CPU
#endif
#else
#include <endian.h>
#if __BITS_PER_LONG == 32
#define MACH_32_BIT_CPU
#else
#define MACH_64_BIT_CPU
#endif
#endif


#ifndef EXIT_SUCCESS
#define EXIT_SUCCESS 0
#define EXIT_FAILURE 1
#endif

#define MACH_SHORT_SIZE 2
#define MACH_INT_SIZE 4
#ifdef MACH_32_BIT_CPU
#define MACH_LONG_SIZE 4
#else
#define MACH_LONG_SIZE 8
#endif
#define MACH_FLOAT_SIZE 4
#define MACH_DOUBLE_SIZE 8

#if BYTE_ORDER == BIG_ENDIAN
#define MACH_BYTE_ORDER_MSB_FIRST
#define MACH_BITFIELDS_MSB_FIRST
#else
#define MACH_BYTE_ORDER_LSB_FIRST
#define MACH_BITFIELDS_LSB_FIRST
#endif

#endif /* __test__ */
