/*
 *      machdep.h generated by machdep at Thu Jan 23 19:50:44 2014
 */

#ifndef __test__
#define __test__

#ifndef EXIT_SUCCESS
#define EXIT_SUCCESS 0
#define EXIT_FAILURE 1
#endif

#define MACH_SHORT_SIZE 2
#define MACH_INT_SIZE 4
#define MACH_LONG_SIZE 8
#define MACH_FLOAT_SIZE 4
#define MACH_DOUBLE_SIZE 8
#define MACH_BYTE_ORDER_LSB_FIRST
#define MACH_BITFIELDS_LSB_FIRST

#endif /* __test__ */
